<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\DataSource;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewsApiSeeder extends seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $data_source = DataSource::create([
            'name' => 'News Api',
            'slug' => 'news_api'
        ]);

        $categories = ["business","entertainment","general","health","science","sports","technology"];

        foreach($categories as $category){
            Category::create(["title" => $category, "data_source" => $data_source->slug]);
        }

        DB::table('sources')->insert(array(
            0 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.',
                    'language' => 'en',
                    'name' => 'ABC News',
                    'source_id' => 'abc-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://abcnews.go.com',
                ),
            1 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'au',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Australia\'s most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.',
                    'language' => 'en',
                    'name' => 'ABC News (AU)',
                    'source_id' => 'abc-news-au',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.abc.net.au/news',
                ),
            2 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'no',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.',
                    'language' => 'no',
                    'name' => 'Aftenposten',
                    'source_id' => 'aftenposten',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.aftenposten.no',
                ),
            3 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.',
                    'language' => 'en',
                    'name' => 'Al Jazeera English',
                    'source_id' => 'al-jazeera-english',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.aljazeera.com',
                ),
            4 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'it',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Agenzia ANSA: ultime notizie, foto, video e approfondimenti su: cronaca, politica, economia, regioni, mondo, sport, calcio, cultura e tecnologia.',
                    'language' => 'it',
                    'name' => 'ANSA.it',
                    'source_id' => 'ansa',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.ansa.it',
                ),
            5 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'sa',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'ارقام موقع متخصص في متابعة سوق الأسهم السعودي تداول - تاسي - مع تغطيه معمقة لشركات واسعار ومنتجات البتروكيماويات , تقارير مالية الاكتتابات الجديده ',
                    'language' => 'ar',
                    'name' => 'Argaam',
                    'source_id' => 'argaam',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.argaam.com',
                ),
            6 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The PC enthusiast\'s resource. Power users and the tools they love, without computing religion.',
                    'language' => 'en',
                    'name' => 'Ars Technica',
                    'source_id' => 'ars-technica',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://arstechnica.com',
                ),
            7 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'pk',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'ARY News is a Pakistani news channel committed to bring you up-to-the minute Pakistan news and featured stories from around Pakistan and all over the world.',
                    'language' => 'ud',
                    'name' => 'Ary News',
                    'source_id' => 'ary-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://arynews.tv/ud/',
                ),
            8 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.',
                    'language' => 'en',
                    'name' => 'Associated Press',
                    'source_id' => 'associated-press',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://apnews.com/',
                ),
            9 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'au',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Australian Financial Review reports the latest news from business, finance, investment and politics, updated in real time. It has a reputation for independent, award-winning journalism and is essential reading for the business and investor community.',
                    'language' => 'en',
                    'name' => 'Australian Financial Review',
                    'source_id' => 'australian-financial-review',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.afr.com',
                ),
            10 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Axios are a new media company delivering vital, trustworthy news and analysis in the most efficient, illuminating and shareable ways possible.',
                    'language' => 'en',
                    'name' => 'Axios',
                    'source_id' => 'axios',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.axios.com',
                ),
            11 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news.',
                    'language' => 'en',
                    'name' => 'BBC News',
                    'source_id' => 'bbc-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.bbc.co.uk/news',
                ),
            12 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The home of BBC Sport online. Includes live sports coverage, breaking news, results, video, audio and analysis on Football, F1, Cricket, Rugby Union, Rugby League, Golf, Tennis and all the main world sports, plus major events such as the Olympic Games.',
                    'language' => 'en',
                    'name' => 'BBC Sport',
                    'source_id' => 'bbc-sport',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.bbc.co.uk/sport',
                ),
            13 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Die Seite 1 für aktuelle Nachrichten und Themen, Bilder und Videos aus den Bereichen News, Wirtschaft, Politik, Show, Sport, und Promis.',
                    'language' => 'de',
                    'name' => 'Bild',
                    'source_id' => 'bild',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.bild.de',
                ),
            14 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'br',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Descubra a seção brasileira da Blasting News, a primeira revista feita pelo  público, com notícias globais e vídeos independentes. Junte-se a nós e torne- se um repórter.',
                    'language' => 'pt',
                    'name' => 'Blasting News (BR)',
                    'source_id' => 'blasting-news-br',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://br.blastingnews.com',
                ),
            15 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!',
                    'language' => 'en',
                    'name' => 'Bleacher Report',
                    'source_id' => 'bleacher-report',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.bleacherreport.com',
                ),
            16 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.',
                    'language' => 'en',
                    'name' => 'Bloomberg',
                    'source_id' => 'bloomberg',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.bloomberg.com',
                ),
            17 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.',
                    'language' => 'en',
                    'name' => 'Breitbart News',
                    'source_id' => 'breitbart-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.breitbart.com',
                ),
            18 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.',
                    'language' => 'en',
                    'name' => 'Business Insider',
                    'source_id' => 'business-insider',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.businessinsider.com',
                ),
            19 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.',
                    'language' => 'en',
                    'name' => 'Business Insider (UK)',
                    'source_id' => 'business-insider-uk',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://uk.businessinsider.com',
                ),
            20 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.',
                    'language' => 'en',
                    'name' => 'Buzzfeed',
                    'source_id' => 'buzzfeed',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.buzzfeed.com',
                ),
            21 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ca',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'CBC News is the division of the Canadian Broadcasting Corporation responsible for the news gathering and production of news programs on the corporation\'s English-language operations, namely CBC Television, CBC Radio, CBC News Network, and CBC.ca.',
                    'language' => 'en',
                    'name' => 'CBC News',
                    'source_id' => 'cbc-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.cbc.ca/news',
                ),
            22 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.',
                    'language' => 'en',
                    'name' => 'CBS News',
                    'source_id' => 'cbs-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.cbsnews.com',
                ),
            23 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN',
                    'language' => 'en',
                    'name' => 'CNN',
                    'source_id' => 'cnn',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://us.cnn.com',
                ),
            24 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Lee las últimas noticias e información sobre Latinoamérica, Estados Unidos, mundo, entretenimiento, política, salud, tecnología y deportes en CNNEspañol.com.',
                    'language' => 'es',
                    'name' => 'CNN Spanish',
                    'source_id' => 'cnn-es',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://cnnespanol.cnn.com/',
                ),
            25 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.',
                    'language' => 'en',
                    'name' => 'Crypto Coins News',
                    'source_id' => 'crypto-coins-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.ccn.com',
                ),
            26 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Nachrichten, News und neueste Meldungen aus dem Inland und dem Ausland - aktuell präsentiert von tagesspiegel.de.',
                    'language' => 'de',
                    'name' => 'Der Tagesspiegel',
                    'source_id' => 'der-tagesspiegel',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.tagesspiegel.de',
                ),
            27 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Aktuelle Nachrichten, Kommentare, Analysen und Hintergrundberichte aus Politik, Wirtschaft, Gesellschaft, Wissen, Kultur und Sport lesen Sie auf ZEIT ONLINE.',
                    'language' => 'de',
                    'name' => 'Die Zeit',
                    'source_id' => 'die-zeit',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.zeit.de/index',
                ),
            28 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'es',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Noticias, actualidad, álbumes, debates, sociedad, servicios, entretenimiento y última hora en España y el mundo.',
                    'language' => 'es',
                    'name' => 'El Mundo',
                    'source_id' => 'el-mundo',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.elmundo.es',
                ),
            29 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.',
                    'language' => 'en',
                    'name' => 'Engadget',
                    'source_id' => 'engadget',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.engadget.com',
                ),
            30 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.',
                    'language' => 'en',
                    'name' => 'Entertainment Weekly',
                    'source_id' => 'entertainment-weekly',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.ew.com',
                ),
            31 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.',
                    'language' => 'en',
                    'name' => 'ESPN',
                    'source_id' => 'espn',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.espn.com',
                ),
            32 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.',
                    'language' => 'en',
                    'name' => 'ESPN Cric Info',
                    'source_id' => 'espn-cric-info',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.espncricinfo.com/',
                ),
            33 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'ca',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Find the latest happenings in the Canadian Financial Sector and stay up to date with changing trends in Business Markets. Read trading and investing advice from professionals.',
                    'language' => 'en',
                    'name' => 'Financial Post',
                    'source_id' => 'financial-post',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://business.financialpost.com',
                ),
            34 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Minutenaktuelle Nachrichten und Service-Informationen von Deutschlands modernem Nachrichtenmagazin.',
                    'language' => 'de',
                    'name' => 'Focus',
                    'source_id' => 'focus',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.focus.de',
                ),
            35 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'it',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Italian football news, analysis, fixtures and results for the latest from Serie A, Serie B and the Azzurri.',
                    'language' => 'en',
                    'name' => 'Football Italia',
                    'source_id' => 'football-italia',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.football-italia.net',
                ),
            36 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Fortune 500 Daily and Breaking Business News',
                    'language' => 'en',
                    'name' => 'Fortune',
                    'source_id' => 'fortune',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://fortune.com',
                ),
            37 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The latest football news, in-depth features, tactical and statistical analysis from FourFourTwo, the UK&#039;s favourite football monthly.',
                    'language' => 'en',
                    'name' => 'FourFourTwo',
                    'source_id' => 'four-four-two',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.fourfourtwo.com/news',
                ),
            38 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.',
                    'language' => 'en',
                    'name' => 'Fox News',
                    'source_id' => 'fox-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.foxnews.com',
                ),
            39 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.',
                    'language' => 'en',
                    'name' => 'Fox Sports',
                    'source_id' => 'fox-sports',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.foxsports.com',
                ),
            40 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'br',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Só na globo.com você encontra tudo sobre o conteúdo e marcas do Grupo Globo. O melhor acervo de vídeos online sobre entretenimento, esportes e jornalismo do Brasil.',
                    'language' => 'pt',
                    'name' => 'Globo',
                    'source_id' => 'globo',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.globo.com/',
                ),
            41 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.',
                    'language' => 'en',
                    'name' => 'Google News',
                    'source_id' => 'google-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            42 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ar',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Completa cobertura actualizada de noticias agregadas a partir de fuentes de todo el mundo por Google Noticias.',
                    'language' => 'es',
                    'name' => 'Google News (Argentina)',
                    'source_id' => 'google-news-ar',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            43 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'au',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Comprehensive, up-to-date Australia news coverage, aggregated from sources all over the world by Google News.',
                    'language' => 'en',
                    'name' => 'Google News (Australia)',
                    'source_id' => 'google-news-au',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            44 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'br',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Cobertura jornalística abrangente e atualizada, agregada de fontes do mundo inteiro pelo Google Notícias.',
                    'language' => 'pt',
                    'name' => 'Google News (Brasil)',
                    'source_id' => 'google-news-br',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            45 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ca',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Comprehensive, up-to-date Canada news coverage, aggregated from sources all over the world by Google News.',
                    'language' => 'en',
                    'name' => 'Google News (Canada)',
                    'source_id' => 'google-news-ca',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            46 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'fr',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Informations complètes et à jour, compilées par Google Actualités à partir de sources d&#39;actualités du monde entier.',
                    'language' => 'fr',
                    'name' => 'Google News (France)',
                    'source_id' => 'google-news-fr',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            47 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'in',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Comprehensive, up-to-date India news coverage, aggregated from sources all over the world by Google News.',
                    'language' => 'en',
                    'name' => 'Google News (India)',
                    'source_id' => 'google-news-in',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            48 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'is',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'כיסוי מקיף ועדכני של חדשות שהצטברו ממקורות בכל העולם על ידי &#39;חדשות Google&#39;.',
                    'language' => 'he',
                    'name' => 'Google News (Israel)',
                    'source_id' => 'google-news-is',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            49 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'it',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Copertura giornalistica completa e aggiornata ottenuta combinando fonti di notizie in tutto il mondo attraverso Google News.',
                    'language' => 'it',
                    'name' => 'Google News (Italy)',
                    'source_id' => 'google-news-it',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            50 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ru',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Исчерпывающая и актуальная информация, собранная службой &quot;Новости Google&quot; со всего света.',
                    'language' => 'ru',
                    'name' => 'Google News (Russia)',
                    'source_id' => 'google-news-ru',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            51 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'sa',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'تغطية شاملة ومتجددة للأخبار، تم جمعها من مصادر أخبار من جميع أنحاء العالم بواسطة أخبار Google.',
                    'language' => 'ar',
                    'name' => 'Google News (Saudi Arabia)',
                    'source_id' => 'google-news-sa',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            52 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Comprehensive, up-to-date UK news coverage, aggregated from sources all over the world by Google News.',
                    'language' => 'en',
                    'name' => 'Google News (UK)',
                    'source_id' => 'google-news-uk',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.google.com',
                ),
            53 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'se',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Göteborgs-Posten, abbreviated GP, is a major Swedish language daily newspaper published in Gothenburg, Sweden.',
                    'language' => 'sv',
                    'name' => 'Göteborgs-Posten',
                    'source_id' => 'goteborgs-posten',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.gp.se',
                ),
            54 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Online-Magazin für Startups und die digitale Wirtschaft. News und Hintergründe zu Investment, VC und Gründungen.',
                    'language' => 'de',
                    'name' => 'Gruenderszene',
                    'source_id' => 'gruenderszene',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.gruenderszene.de',
                ),
            55 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham\'s investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as "anything that gratifies one\'s intellectual curiosity".',
                    'language' => 'en',
                    'name' => 'Hacker News',
                    'source_id' => 'hacker-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.ycombinator.com',
                ),
            56 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Auf Handelsblatt lesen sie Nachrichten über Unternehmen, Finanzen, Politik und Technik. Verwalten Sie Ihre Finanzanlagen mit Hilfe unserer Börsenkurse.',
                    'language' => 'de',
                    'name' => 'Handelsblatt',
                    'source_id' => 'handelsblatt',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.handelsblatt.com',
                ),
            57 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'IGN is your site for Xbox One, PS4, PC, Wii-U, Xbox 360, PS3, Wii, 3DS, PS Vita and iPhone games with expert reviews, news, previews, trailers, cheat codes, wiki guides and walkthroughs.',
                    'language' => 'en',
                    'name' => 'IGN',
                    'source_id' => 'ign',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.ign.com',
                ),
            58 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'it',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Notizie di economia, cronaca italiana ed estera, quotazioni borsa in tempo reale e di finanza, norme e tributi, fondi e obbligazioni, mutui, prestiti e lavoro a cura de Il Sole 24 Ore.',
                    'language' => 'it',
                    'name' => 'Il Sole 24 Ore',
                    'source_id' => 'il-sole-24-ore',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.ilsole24ore.com',
                ),
            59 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'National morning quality (tabloid) includes free online access to news and supplements. Insight by Robert Fisk and various other columnists.',
                    'language' => 'en',
                    'name' => 'Independent',
                    'source_id' => 'independent',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.independent.co.uk',
                ),
            60 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'br',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'No InfoMoney você encontra tudo o que precisa sobre dinheiro. Ações, investimentos, bolsas de valores e muito mais. Aqui você encontra informação que vale dinheiro!',
                    'language' => 'pt',
                    'name' => 'InfoMoney',
                    'source_id' => 'info-money',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.infomoney.com.br',
                ),
            61 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ar',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Noticias de Argentina y del mundo en tiempo real. Información, videos y fotos sobre los hechos más relevantes y sus protagonistas. Léelo antes en infobae.',
                    'language' => 'es',
                    'name' => 'Infobae',
                    'source_id' => 'infobae',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.infobae.com/?noredirect',
                ),
            62 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ar',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'El diario de Tucumán, noticias 24 horas online - San Miguel de Tucumán - Argentina - Ultimo momento - Ultimas noticias.',
                    'language' => 'es',
                    'name' => 'La Gaceta',
                    'source_id' => 'la-gaceta',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.lagaceta.com.ar',
                ),
            63 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ar',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Información confiable en Internet. Noticias de Argentina y del mundo - ¡Informate ya!',
                    'language' => 'es',
                    'name' => 'La Nacion',
                    'source_id' => 'la-nacion',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.lanacion.com.ar',
                ),
            64 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'it',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.',
                    'language' => 'it',
                    'name' => 'La Repubblica',
                    'source_id' => 'la-repubblica',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.repubblica.it',
                ),
            65 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'fr',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Les articles du journal et toute l\'actualit&eacute; en continu : International, France, Soci&eacute;t&eacute;, Economie, Culture, Environnement, Blogs ...',
                    'language' => 'fr',
                    'name' => 'Le Monde',
                    'source_id' => 'le-monde',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.lemonde.fr',
                ),
            66 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ru',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Новости, статьи, фотографии, видео. Семь дней в неделю, 24 часа в сутки.',
                    'language' => 'ru',
                    'name' => 'Lenta',
                    'source_id' => 'lenta',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://lenta.ru',
                ),
            67 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'fr',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Le sport en direct sur L\'EQUIPE.fr. Les informations, résultats et classements de tous les sports. Directs commentés, images et vidéos à regarder et à partager !',
                    'language' => 'fr',
                    'name' => 'L\'equipe',
                    'source_id' => 'lequipe',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.lequipe.fr',
                ),
            68 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'fr',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Toute l\'actualité économique, financière et boursière française et internationale sur Les Echos.fr',
                    'language' => 'fr',
                    'name' => 'Les Echos',
                    'source_id' => 'les-echos',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.lesechos.fr',
                ),
            69 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'fr',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Toute l\'actualité en direct - photos et vidéos avec Libération',
                    'language' => 'fr',
                    'name' => 'Libération',
                    'source_id' => 'liberation',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.liberation.fr',
                ),
            70 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'es',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'La mejor información deportiva en castellano actualizada minuto a minuto en noticias, vídeos, fotos, retransmisiones y resultados en directo.',
                    'language' => 'es',
                    'name' => 'Marca',
                    'source_id' => 'marca',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.marca.com',
                ),
            71 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Mashable is a global, multi-platform media and entertainment company.',
                    'language' => 'en',
                    'name' => 'Mashable',
                    'source_id' => 'mashable',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://mashable.com',
                ),
            72 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'health',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Medical news and health news headlines posted throughout the day, every day.',
                    'language' => 'en',
                    'name' => 'Medical News Today',
                    'source_id' => 'medical-news-today',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.medicalnewstoday.com',
                ),
            73 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.',
                    'language' => 'en',
                    'name' => 'MSNBC',
                    'source_id' => 'msnbc',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.msnbc.com',
                ),
            74 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It\'s pop culture on steroids.',
                    'language' => 'en',
                    'name' => 'MTV News',
                    'source_id' => 'mtv-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.mtv.com/news',
                ),
            75 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'All the latest celebrity news, gossip, exclusive interviews and pictures from the world of music and entertainment.',
                    'language' => 'en',
                    'name' => 'MTV News (UK)',
                    'source_id' => 'mtv-news-uk',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.mtv.co.uk/news',
                ),
            76 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'science',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Reporting our world daily: original nature and science news from National Geographic.',
                    'language' => 'en',
                    'name' => 'National Geographic',
                    'source_id' => 'national-geographic',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://news.nationalgeographic.com',
                ),
            77 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'National Review: Conservative News, Opinion, Politics, Policy, & Current Events.',
                    'language' => 'en',
                    'name' => 'National Review',
                    'source_id' => 'national-review',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.nationalreview.com/',
                ),
            78 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.',
                    'language' => 'en',
                    'name' => 'NBC News',
                    'source_id' => 'nbc-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.nbcnews.com',
                ),
            79 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'science',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.',
                    'language' => 'en',
                    'name' => 'New Scientist',
                    'source_id' => 'new-scientist',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.newscientist.com/section/news',
                ),
            80 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.',
                    'language' => 'en',
                    'name' => 'New York Magazine',
                    'source_id' => 'new-york-magazine',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://nymag.com',
                ),
            81 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'au',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'We say what people are thinking and cover the issues that get people talking balancing Australian and global moments — from politics to pop culture.',
                    'language' => 'en',
                    'name' => 'News.com.au',
                    'source_id' => 'news-com-au',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.news.com.au',
                ),
            82 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'za',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'South Africa\'s premier news source, provides breaking news on national, world, Africa, sport, entertainment, technology and more.',
                    'language' => 'en',
                    'name' => 'News24',
                    'source_id' => 'news24',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.news24.com',
                ),
            83 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.',
                    'language' => 'en',
                    'name' => 'Newsweek',
                    'source_id' => 'newsweek',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.newsweek.com',
                ),
            84 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'science',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.',
                    'language' => 'en',
                    'name' => 'Next Big Future',
                    'source_id' => 'next-big-future',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.nextbigfuture.com',
                ),
            85 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The official source for NFL news, schedules, stats, scores and more.',
                    'language' => 'en',
                    'name' => 'NFL News',
                    'source_id' => 'nfl-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.nfl.com/news',
                ),
            86 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.',
                    'language' => 'en',
                    'name' => 'NHL News',
                    'source_id' => 'nhl-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.nhl.com/news',
                ),
            87 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'no',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'NRK er Norges største tilbud på nett: nyheter fra Norge og verden, lokalnyheter, radio- og tv-program, podcast, vær, helse-, kultur-, underholdning-, humor- og debattstoff.',
                    'language' => 'no',
                    'name' => 'NRK',
                    'source_id' => 'nrk',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.nrk.no',
                ),
            88 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Political news about Congress, the White House, campaigns, lobbyists and issues.',
                    'language' => 'en',
                    'name' => 'Politico',
                    'source_id' => 'politico',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.politico.com',
                ),
            89 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.',
                    'language' => 'en',
                    'name' => 'Polygon',
                    'source_id' => 'polygon',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.polygon.com',
                ),
            90 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ru',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Главные новости политики, экономики и бизнеса, комментарии аналитиков, финансовые данные с российских и мировых биржевых систем на сайте rbc.ru.',
                    'language' => 'ru',
                    'name' => 'RBC',
                    'source_id' => 'rbc',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.rbc.ru',
                ),
            91 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.',
                    'language' => 'en',
                    'name' => 'Recode',
                    'source_id' => 'recode',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.recode.net',
                ),
            92 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Reddit is an entertainment, social news networking service, and news website. Reddit\'s registered community members can submit content, such as text posts or direct links.',
                    'language' => 'en',
                    'name' => 'Reddit /r/all',
                    'source_id' => 'reddit-r-all',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.reddit.com/r/all',
                ),
            93 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Reuters.com brings you the latest news from around the world, covering breaking news in business, politics, entertainment, technology, video and pictures.',
                    'language' => 'en',
                    'name' => 'Reuters',
                    'source_id' => 'reuters',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.reuters.com',
                ),
            94 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ru',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Актуальная картина дня на RT: круглосуточное ежедневное обновление новостей политики, бизнеса, финансов, спорта, науки, культуры. Онлайн-репортажи с места событий. Комментарии экспертов, актуальные интервью, фото и видео репортажи.',
                    'language' => 'ru',
                    'name' => 'RT',
                    'source_id' => 'rt',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://russian.rt.com',
                ),
            95 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ie',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Get all of the latest breaking local and international news stories as they happen, with up to the minute updates and analysis, from Ireland\'s National Broadcaster.',
                    'language' => 'en',
                    'name' => 'RTE',
                    'source_id' => 'rte',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.rte.ie/news',
                ),
            96 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'nl',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Volg het nieuws terwijl het gebeurt. RTL Nieuws informeert haar lezers op een onafhankelijke, boeiende en toegankelijke wijze over belangrijke ontwikkelingen in eigen land en de rest van de wereld.',
                    'language' => 'nl',
                    'name' => 'RTL Nieuws',
                    'source_id' => 'rtl-nieuws',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.rtlnieuws.nl/',
                ),
            97 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'sa',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'صحيفة الكترونية سعودية هدفها السبق في نقل الحدث بمهنية ومصداقية خدمة للوطن والمواطن.',
                    'language' => 'ar',
                    'name' => 'SABQ',
                    'source_id' => 'sabq',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://sabq.org',
                ),
            98 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Deutschlands führende Nachrichtenseite. Alles Wichtige aus Politik, Wirtschaft, Sport, Kultur, Wissenschaft, Technik und mehr.',
                    'language' => 'de',
                    'name' => 'Spiegel Online',
                    'source_id' => 'spiegel-online',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.spiegel.de',
                ),
            99 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'se',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Sveriges ledande mediesajt - SvD.se. Svenska Dagbladets nyhetssajt låter läsarna ta plats och fördjupar nyheterna.',
                    'language' => 'sv',
                    'name' => 'Svenska Dagbladet',
                    'source_id' => 'svenska-dagbladet',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.svd.se',
                ),
            100 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Das Online-Magazin bietet Artikel zu den Themen E-Business, Social Media, Startups und Webdesign.',
                    'language' => 'de',
                    'name' => 'T3n',
                    'source_id' => 't3n',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://t3n.de',
                ),
            101 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Tune in to the world\'s biggest sports radio station - Live Premier League football coverage, breaking sports news, transfer rumours &amp; exclusive interviews.',
                    'language' => 'en',
                    'name' => 'TalkSport',
                    'source_id' => 'talksport',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://talksport.com',
                ),
            102 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.',
                    'language' => 'en',
                    'name' => 'TechCrunch',
                    'source_id' => 'techcrunch',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://techcrunch.com',
                ),
            103 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'zh',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.',
                    'language' => 'zh',
                    'name' => 'TechCrunch (CN)',
                    'source_id' => 'techcrunch-cn',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://techcrunch.cn',
                ),
            104 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.',
                    'language' => 'en',
                    'name' => 'TechRadar',
                    'source_id' => 'techradar',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.techradar.com',
                ),
            105 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Realism and reform. A new voice for a new generation of conservatives.',
                    'language' => 'en',
                    'name' => 'The American Conservative',
                    'source_id' => 'the-american-conservative',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.theamericanconservative.com/',
                ),
            106 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ca',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Globe and Mail offers the most authoritative news in Canada, featuring national and international news.',
                    'language' => 'en',
                    'name' => 'The Globe And Mail',
                    'source_id' => 'the-globe-and-mail',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.theglobeandmail.com',
                ),
            107 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Hill is a top US political website, read by the White House and more lawmakers than any other site -- vital for policy, politics and election campaigns.',
                    'language' => 'en',
                    'name' => 'The Hill',
                    'source_id' => 'the-hill',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://thehill.com',
                ),
            108 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'in',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Hindu. latest news, analysis, comment, in-depth coverage of politics, business, sport, environment, cinema and arts from India\'s national newspaper.',
                    'language' => 'en',
                    'name' => 'The Hindu',
                    'source_id' => 'the-hindu',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.thehindu.com',
                ),
            109 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Huffington Post is a politically liberal American online news aggregator and blog that has both localized and international editions founded by Arianna Huffington, Kenneth Lerer, Andrew Breitbart, and Jonah Peretti, featuring columnists.',
                    'language' => 'en',
                    'name' => 'The Huffington Post',
                    'source_id' => 'the-huffington-post',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.huffingtonpost.com',
                ),
            110 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'ie',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Irish Times online. Latest news including sport, analysis, business, weather and more from the definitive brand of quality news in Ireland.',
                    'language' => 'en',
                    'name' => 'The Irish Times',
                    'source_id' => 'the-irish-times',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.irishtimes.com',
                ),
            111 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'is',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Jerusalem Post is the leading online newspaper for English speaking Jewry since 1932, bringing news and updates from the Middle East and all over the Jewish world.',
                    'language' => 'en',
                    'name' => 'The Jerusalem Post',
                    'source_id' => 'the-jerusalem-post',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.jpost.com/',
                ),
            112 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'entertainment',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The LAD Bible is one of the largest community for guys aged 16-30 in the world. Send us your funniest pictures and videos!',
                    'language' => 'en',
                    'name' => 'The Lad Bible',
                    'source_id' => 'the-lad-bible',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.theladbible.com',
                ),
            113 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Next Web is one of the world’s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.',
                    'language' => 'en',
                    'name' => 'The Next Web',
                    'source_id' => 'the-next-web',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://thenextweb.com',
                ),
            114 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'sports',
                    'country' => 'gb',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'TheSPORTbible is one of the largest communities for sports fans across the world. Send us your sporting pictures and videos!',
                    'language' => 'en',
                    'name' => 'The Sport Bible',
                    'source_id' => 'the-sport-bible',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.thesportbible.com',
                ),
            115 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'in',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Times of India brings the Latest News and Top Breaking headlines on Politics and Current Affairs in India and around the World, Sports, Business, Bollywood News and Entertainment, Science, Technology, Health and Fitness news, Cricket and opinions from leading columnists.',
                    'language' => 'en',
                    'name' => 'The Times of India',
                    'source_id' => 'the-times-of-india',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://timesofindia.indiatimes.com',
                ),
            116 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Verge covers the intersection of technology, science, art, and culture.',
                    'language' => 'en',
                    'name' => 'The Verge',
                    'source_id' => 'the-verge',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.theverge.com',
                ),
            117 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'WSJ online coverage of breaking news and current headlines from the US and around the world. Top stories, photos, videos, detailed analysis and in-depth reporting.',
                    'language' => 'en',
                    'name' => 'The Wall Street Journal',
                    'source_id' => 'the-wall-street-journal',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.wsj.com',
                ),
            118 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.',
                    'language' => 'en',
                    'name' => 'The Washington Post',
                    'source_id' => 'the-washington-post',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.washingtonpost.com',
                ),
            119 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'The Washington Times delivers breaking news and commentary on the issues that affect the future of our nation.',
                    'language' => 'en',
                    'name' => 'The Washington Times',
                    'source_id' => 'the-washington-times',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.washingtontimes.com/',
                ),
            120 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.',
                    'language' => 'en',
                    'name' => 'Time',
                    'source_id' => 'time',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://time.com',
                ),
            121 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Get the latest national, international, and political news at USATODAY.com.',
                    'language' => 'en',
                    'name' => 'USA Today',
                    'source_id' => 'usa-today',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.usatoday.com/news',
                ),
            122 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Vice News is Vice Media, Inc.\'s current affairs channel, producing daily documentary essays and video through its website and YouTube channel. It promotes itself on its coverage of "under - reported stories".',
                    'language' => 'en',
                    'name' => 'Vice News',
                    'source_id' => 'vice-news',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://news.vice.com',
                ),
            123 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'us',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.',
                    'language' => 'en',
                    'name' => 'Wired',
                    'source_id' => 'wired',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.wired.com',
                ),
            124 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'technology',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Wired reports on how emerging technologies affect culture, the economy and politics.',
                    'language' => 'de',
                    'name' => 'Wired.de',
                    'source_id' => 'wired-de',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'https://www.wired.de',
                ),
            125 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'business',
                    'country' => 'de',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'Das Online-Portal des führenden Wirtschaftsmagazins in Deutschland. Das Entscheidende zu Unternehmen, Finanzen, Erfolg und Technik.',
                    'language' => 'de',
                    'name' => 'Wirtschafts Woche',
                    'source_id' => 'wirtschafts-woche',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.wiwo.de',
                ),
            126 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'zh',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => '中国主要重点新闻网站,依托新华社遍布全球的采编网络,记者遍布世界100多个国家和地区,地方频道分布全国31个省市自治区,每天24小时同时使用6种语言滚动发稿,权威、准确、及时播发国内外重要新闻和重大突发事件,受众覆盖200多个国家和地区,发展论坛是全球知名的中文论坛。',
                    'language' => 'zh',
                    'name' => 'Xinhua Net',
                    'source_id' => 'xinhua-net',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://xinhuanet.com/',
                ),
            127 =>
                array(
                    'data_source' => 'news_api',
                    'category' => 'general',
                    'country' => 'is',
                    'created_at' => '2023-06-24 22:18:01',
                    'description' => 'ynet דף הבית: אתר החדשות המוביל בישראל מבית ידיעות אחרונות. סיקור מלא של חדשות מישראל והעולם, ספורט, כלכלה, תרבות, אוכל, מדע וטבע, כל מה שקורה וכל מה שמעניין ב ynet.',
                    'language' => 'he',
                    'name' => 'Ynet',
                    'source_id' => 'ynet',
                    'updated_at' => '2023-06-24 22:18:01',
                    'url' => 'http://www.ynet.co.il',
                ),
        ));

    }
}

